package com.devepos.adt.saat.ui.internal.help;

/**
 * Holds Help Contexts
 *
 * @author stockbal
 */
public enum HelpContextId {
  OBJECT_SEARCH,
  OBJECT_SEARCH_DIALOG,
  OBJECT_SEARCH_RESULT,
  CDS_ANALYZER,
  CDS_ANALYZER_TOP_DOWN_ANALYSIS,
  CDS_ANALYZER_WHERE_USED_ANALYSIS,
  CDS_ANALYZER_USED_ENTITIES_ANALYSIS,
  CDS_ANALYZER_FIELD_ANALYSIS,
  ANALYSIS_TYPE_CONFIG;
}
