name: ❓ Question
description: Ask a question
title: "[QUESTION] "
labels: 
  - question
assignees: stockbal  
body:
  - type: textarea
    attributes:
      label: Question
      description: What would you like to know? If you encounter unusual behaviour or identified a missing feature, consider opening a bug report instead.
    validations:
      required: true
