name: Bump Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 1.1.1)"
        required: true
      commitScope:
        description: "Commit scope (e.g. core, tags, codesearch)"
        required: true
      projectPath:
        description: "Path to root of project"
        required: true

permissions:
  contents: write
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Bump version of project
      run: |
        cd ./${{ github.event.inputs.projectPath }}
        mvn tycho-versions:set-version -DnewVersion="${{ github.event.inputs.version }}-SNAPSHOT" -q

    - name: Check for Changes
      id: check_changes
      run: |
        if [[ -n "$(git diff --exit-code)" ]]; then
          echo "Changes detected."
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
        else
          echo "No changes detected."
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit and Push Changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        # configure user
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        # stage any file changes to be committed
        git add .

        # make commit with staged changes
        git commit -m "chore(${{ github.event.inputs.commitScope }}): bump version to v${{ github.event.inputs.version }}"

        # push the commit back up to source GitHub repository
        git push        