name: Trigger publishing of BETA update site
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: 

jobs:
  trigger-deployment:
    uses: DevEpos/eclipse.devepos.com/.github/workflows/deploy-to-beta.yml@main
    with:
      source-branch: ${{ github.ref_name }}
    secrets: inherit